(defun  is-linux ()
  (interactive)
  "判断是否是 linux 系统，是返回 '(linux) 否返回 nil"
  (if (or (eq system-type 'gnu/linux) (eq system-type 'linux))
      '(linux)
      )
	)
(defun is-win64 ()
  (interactive)
  (if (eq system-type 'windows-nt)
      '(win64)
      )
	)

(defun is-mac ()
  (interactive)
  (if (eq system-type 'darwin)
      '(mac)
      )
	)

(defun which-os()
  (interactive)
  (seq-find
   (lambda (i) (not (eq nil i)) )
   (list (is-mac) (is-win64) (is-linux))
  )
  )

(provide 'os)
